apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- controller-registration.yaml

patches:
- patch: |
    - op: replace
      path: /helm/values
      value:
        image:
          ref: local-skaffold/gardener-extension-auditing
  target:
    group: core.gardener.cloud
    kind: ControllerDeployment
    name: auditing
