---
apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: extension
build:
  insecureRegistries:
    - garden.local.gardener.cloud:5001
  tagPolicy:
    customTemplate:
      template: "{{.version}}-{{.sha}}"
      components:
        - name: version
          envTemplate:
            template: "{{.EXTENSION_VERSION}}"
        # inputDigest is used to inject a digest of the artifact source into the built image tag
        # and therefore into the SKAFFOLD_IMAGE environment variable which is used when generating the corresponding ControllerDeployment
        - name: sha
          inputDigest: {}
  artifacts:
    - image: local-skaffold/gardener-extension-auditing
      ko:
        dependencies:
          paths:
            - cmd/gardener-extension-auditing
            - cmd/gardener-extension-auditing/app
            - imagevector
            - imagevector/images.yaml
            - pkg/apis/auditing
            - pkg/apis/auditing/install
            - pkg/apis/auditing/v1alpha1
            - pkg/apis/config
            - pkg/apis/config/v1alpha1
            - pkg/apis/config/validation
            - pkg/cmd
            - pkg/component/auditlog-forwarder
            - pkg/constants
            - pkg/controller/audit
            - pkg/controller/healthcheck
            - pkg/secrets
            - pkg/webhook/kapiserver
            - VERSION
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/gardener-extension-auditing
    - image: local-skaffold/echo-server
      ko:
        dependencies:
          paths:
            - cmd/echo-server
            - VERSION
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/echo-server
manifests:
  kustomize:
    paths:
      - example
resourceSelector:
  # instruct skaffold to inject the built image reference into the image field in our ControllerDeployment
  allow:
    - groupKind: ControllerDeployment.core.gardener.cloud
      image:
        - .helm.values.image.ref
deploy:
  # --server-side apply is a workaround for https://github.com/gardener/gardener/issues/10267.
  # kubectl apply attempts a strategic merge patch which fails for a ControllerDeployment.
  # For more details, see https://github.com/gardener/gardener/issues/10267.
  #
  # TODO: Switch back to "kubectl: {}" when the above issue is resolved.
  kubectl:
    flags:
      apply:
        - --server-side
        - --force-conflicts
  helm:
    releases:
      - name: echo-server
        chartPath: example/local-setup/charts/echo-server
        valuesFiles:
          - example/local-setup/charts/echo-server/values.yaml
        namespace: echo-server
        setValueTemplates:
          image.repository: '{{.IMAGE_REPO_local_skaffold_echo_server}}'
          image.tag: '{{.IMAGE_TAG_local_skaffold_echo_server}}@{{.IMAGE_DIGEST_local_skaffold_echo_server}}'
        setFiles:
          certificates.ca.crt: example/local-setup/dev/certs/ca.crt
          certificates.tls.crt: example/local-setup/dev/certs/echo-server-tls.crt
          certificates.tls.key: example/local-setup/dev/certs/echo-server-tls.key
          certificates.client.crt: example/local-setup/dev/certs/client.crt
          certificates.client.key: example/local-setup/dev/certs/client.key
        createNamespace: true
        wait: true
    hooks:
      before:
        - host:
            command:
              - bash
              - -ec
              - hack/cert-gen.sh
