---
apiVersion: v1
kind: Secret
metadata:
  name: echo-server-creds
  namespace: garden-local
type: Opaque
data:
  ca.crt: {{ .Values.certificates.ca.crt | b64enc | quote }}
  client.crt: {{ .Values.certificates.client.crt | b64enc | quote }}
  client.key: {{ .Values.certificates.client.key | b64enc | quote }}
