---
apiVersion: v1
kind: Secret
metadata:
  name: echo-server-tls
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: echo-server
    app.kubernetes.io/instance: {{ .Release.Name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.certificates.tls.crt | b64enc }}
  tls.key: {{ .Values.certificates.tls.key | b64enc }}
