---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: echo-server
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: {{ .Values.config.port }}
    protocol: TCP
  - name: health
    port: 8080
    targetPort: {{ .Values.config.healthPort }}
    protocol: TCP
  selector:
    app.kubernetes.io/name: echo-server
    app.kubernetes.io/instance: {{ .Release.Name }}
