apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-policy-garden
  namespace: garden
data:
  policy: |
    apiVersion: audit.k8s.io/v1
    kind: Policy
    omitStages:
    - RequestReceived
    rules:
    - level: Request
      namespaces:
      - garden-local
      verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
      resources:
      - group: core.gardener.cloud
        resources:
        - shoots
